#!/usr/bin/env bash

# Runs tests for a specific product

set -ex

# get this scripts directory
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

cd "$SCRIPT_DIR"/../ || exit 1
ARGS=${ARGS:=}
FOLDER=${FOLDER:=./integration-tests/smoke}
SELECTED_NETWORKS="SIMULATED,SIMULATED_1,SIMULATED_2" \
	ginkgo -v -r --junit-report=tests-smoke-report.xml \
	--keep-going --trace --randomize-all --randomize-suites \
	${ARGS} \
	${FOLDER}